Mission4Assignment/Models/GradeCalculatorModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Mission4Assignment.Models
{
    public class GradeCalculatorModel
    {
        [Range(0, 100, ErrorMessage = "Must be a number between 0 and 100.")]
        [Required]
        public string assignment { get; set; }
        [Range(0, 100, ErrorMessage = "Must be a number between 0 and 100.")]
        [Required]
        public string project { get; set; }
        [Range(0, 100, ErrorMessage = "Must be a number between 0 and 100.")]
        [Required]
        public string quiz { get; set; }
        [Range(0, 100, ErrorMessage = "Must be a number between 0 and 100.")]
        [Required]
        public string midterm { get; set; }
        [Range(0, 100, ErrorMessage = "Must be a number between 0 and 100.")]
        [Required]
        public string final { get; set; }
        [Range(0, 100, ErrorMessage = "Must be a number between 0 and 100.")]
        [Required]
        public string intex { get; set; }

    }
}

Mission4Assignment/Controllers/StuffController.cs
using Microsoft.AspNetCore.Mvc;
using Mission4Assignment.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission4Assignment.Controllers
{
    public class StuffController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult GradeCalculator()
        {
            return View();
        }
        [HttpPost]
        public IActionResult GradeCalculator(GradeCalculatorModel gcm)
        {
            return View();
        }
    }
}

Mission4Assignment/Views/Stuff/GradeCalculator.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

}

@model GradeCalculatorModel

<!-- Form for Grade Calculator -->

<div>
    <fieldset>
        <form method="post">
            <label style="padding-left:15px;" id="assignments">Assignments: </label>
            <input type="text" id="txtAssignment" asp-for="assignment" /><br /><br />
            <label style="padding-left:15px;" id="groupProject">Group Project: </label>
            <input type="text" id="txtGroupProject" asp-for="project" /><br /><br />
            <label style="padding-left:15px;" id="quizzes">Quizzes: </label>
            <input type="text" id="txtQuiz" asp-for="quiz" /><br /><br />
            <label style="padding-left:15px;" id="midterm">Midterm Exam: </label>
            <input type="text" id="txtMidtermExam" asp-for="midterm" /><br /><br />
            <label style="padding-left:15px;" id="finalExam">Final Exam: </label>
            <input type="text" id="txtFinalExam" asp-for="final" /><br /><br />
            <label style="padding-left:15px;" id="intex">INTEX: </label>
            <input type="text" id="txtINTEX" asp-for="intex" /><br /><br /><br />
            <button id="btnCalc" type="submit">Calculate</button>
        </form>
    </fieldset>
    <div asp-validation-summary="All"></div>
</div>

<p id="percentage"></p>
<p id="letterGrade"></p>

Mission4Assignment/Views/Stuff/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Home Page";
}

    <!-- header title -->
    <h1>Ella's Home Page!</h1>
    <!-- Image  -->
    <img id="picEllaFun" style="width:200px;" src="img/2DC8DA15-6443-41F6-BE46-97ECB83E7350.JPG" />
    <!-- What I want to get out of this class -->
    <p>I hope to get an A out of this class, because honestly sometimes I wonder if I am going to make it to the next class period. I also want to master C# to have another language under my belt. I also want to further my development skills, and keep them fresh for my internship ths summer. I want to get faster, more efficient, and cleaner with my code structure, and I believe practice and dedication to this class will help me accomplish that. </p>

    <!-- Output for percentage and resulting letter grade -->
    <p id="percentage"></p>
    <p id="letterGrade"></p>

    <!-- Top 3 Jobs -->
    <h2>My Top 3 Jobs: </h2>
    <ul>
        <li>#1: Cybersecurity Software Engineer</li>
        <li>#2: Web Designer </li>
        <li>#3: Business Analytics </li>
    </ul>

Mission4Assignment/Views/Stuff/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"]</title>
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />

    <link rel="icon" type="image/x-icon" href="img/5195638.png">
    <link rel="stylesheet" href="~/css/styles.css">
</head>

<body>
    <nav>
        <a asp-controller="Stuff" asp-action="Index">Home</a>
        <a asp-controller="Stuff" asp-action="GradeCalculator">Grade Calculator</a>
    </nav>

    <div>
        @RenderBody()
    </div>

    <script src="~/js/lib/jquery/jquery-3.6.3.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/js/lib/GradeCalculator.js"></script>

</body>
</html>